In [695]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib import ticker
import matplotlib.ticker as mticker

In [696]:
df_Telemedicine = pd.read_csv('./Resources/Telemedicine_Use_in_the_Last_4_Weeks_20240409.csv')
df_tmed_dy21 = pd.read_csv('./Resources/TMED_DY21_public_20220106.csv')
df_tmedtrend = pd.read_csv('./Resources/TMEDTREND_PUBLIC_240306.csv')
df_access = pd.read_csv('./Resources/Access_and_Use_of_Telemedicine_During_COVID-19.csv')

In [697]:
# Display the first few rows of the DataFrame
print(df_Telemedicine.head())

# Display the DataFrame's information, including the data types and non-null values
df_Telemedicine.info()

# Get summary statistics for numerical columns
print(df_Telemedicine.describe())

                                           Indicator              Group  \
0  Adults Who Had Appointment with Health Profess...  National Estimate
1  Adults Who Had Appointment with Health Profess...             By Age
2  Adults Who Had Appointment with Health Profess...             By Age
3  Adults Who Had Appointment with Health Profess...             By Age
4  Adults Who Had Appointment with Health Profess...             By Age

           State       Subgroup  Phase  Time Period      Time Period Label  \
0  United States  United States    3.1           28  Apr 14 - Apr 26, 2021
1  United States  18 - 29 years    3.1           28  Apr 14 - Apr 26, 2021
2  United States  30 - 39 years    3.1           28  Apr 14 - Apr 26, 2021
3  United States  40 - 49 years    3.1           28  Apr 14 - Apr 26, 2021
4  United States  50 - 59 years    3.1           28  Apr 14 - Apr 26, 2021

  Time Period Start Date Time Period End Date  Value  Low CI  High CI  \
0             04/14/2021           04/26/2021   25.7    25.0     26.4
1             04/14/2021           04/26/2021   21.6    19.2     24.1
2             04/14/2021           04/26/2021   23.1    21.7     24.5
3             04/14/2021           04/26/2021   25.7    24.2     27.3
4             04/14/2021           04/26/2021   26.3    24.6     28.1

  Confidence Interval Quartile Range  Suppression Flag
0         25.0 - 26.4            NaN               NaN
1         19.2 - 24.1            NaN               NaN
2         21.7 - 24.5            NaN               NaN
3         24.2 - 27.3            NaN               NaN
4         24.6 - 28.1            NaN               NaN
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3344 entries, 0 to 3343
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Indicator               3344 non-null   object
 1   Group                   3344 non-null   object
 2   State                   3344 non-null   object
 3   Subgroup                3344 non-null   object
 4   Phase                   3344 non-null   float64
 5   Time Period             3344 non-null   int64
 6   Time Period Label       3344 non-null   object
 7   Time Period Start Date  3344 non-null   object
 8   Time Period End Date    3344 non-null   object
 9   Value                   3104 non-null   float64
 10  Low CI                  3104 non-null   float64
 11  High CI                 3104 non-null   float64
 12  Confidence Interval     3104 non-null   object
 13  Quartile Range          2142 non-null   object
 14  Suppression Flag        52 non-null     float64
dtypes: float64(5), int64(1), object(9)
memory usage: 392.0+ KB
             Phase  Time Period        Value       Low CI      High CI  \
count  3344.000000  3344.000000  3104.000000  3104.000000  3104.000000
mean      3.019498    36.000598    19.605638    15.760374    24.118814
std       0.990528    10.361604     5.368918     5.482188     5.889849
min      -1.000000     1.000000     6.800000     3.800000    10.800000
25%       3.100000    32.000000    15.800000    11.900000    19.900000
50%       3.200000    37.500000    19.250000    15.400000    23.500000
75%       3.400000    43.000000    23.000000    19.700000    27.500000
max       3.500000    48.000000    44.900000    39.200000    57.400000

       Suppression Flag
count              52.0
mean                1.0
std                 0.0
min                 1.0
25%                 1.0
50%                 1.0
75%                 1.0
max                 1.0

In [698]:
df_Telemedicine

,Indicator,Group,State,Subgroup,Phase,Time Period,Time Period Label,Time Period Start Date,Time Period End Date,Value,Low CI,High CI,Confidence Interval,Quartile Range,Suppression Flag
0,Adults Who Had Appointment with Health Profess...,National Estimate,United States,United States,3.1,28,"Apr 14 - Apr 26, 2021",04/14/2021,04/26/2021,25.7,25.0,26.4,25.0 - 26.4,NaN,NaN
1,Adults Who Had Appointment with Health Profess...,By Age,United States,18 - 29 years,3.1,28,"Apr 14 - Apr 26, 2021",04/14/2021,04/26/2021,21.6,19.2,24.1,19.2 - 24.1,NaN,NaN
2,Adults Who Had Appointment with Health Profess...,By Age,United States,30 - 39 years,3.1,28,"Apr 14 - Apr 26, 2021",04/14/2021,04/26/2021,23.1,21.7,24.5,21.7 - 24.5,NaN,NaN
3,Adults Who Had Appointment with Health Profess...,By Age,United States,40 - 49 years,3.1,28,"Apr 14 - Apr 26, 2021",04/14/2021,04/26/2021,25.7,24.2,27.3,24.2 - 27.3,NaN,NaN
4,Adults Who Had Appointment with Health Profess...,By Age,United States,50 - 59 years,3.1,28,"Apr 14 - Apr 26, 2021",04/14/2021,04/26/2021,26.3,24.6,28.1,24.6 - 28.1,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3339,Households With Children Where Any Child Had A...,By State,Virginia,Virginia,3.5,48,"Jul 27 - Aug 8, 2022",07/27/2022,08/08/2022,18.8,12.9,26.1,12.9 - 26.1,18.2-23.1,NaN
3340,Households With Children Where Any Child Had A...,By State,Washington,Washington,3.5,48,"Jul 27 - Aug 8, 2022",07/27/2022,08/08/2022,18.9,15.1,23.3,15.1 - 23.3,18.2-23.1,NaN
3341,Households With Children Where Any Child Had A...,By State,West Virginia,West Virginia,3.5,48,"Jul 27 - Aug 8, 2022",07/27/2022,08/08/2022,NaN,NaN,NaN,NaN,Estimate is not reliable.,1.0
3342,Households With Children Where Any Child Had A...,By State,Wisconsin,Wisconsin,3.5,48,"Jul 27 - Aug 8, 2022",07/27/2022,08/08/2022,13.8,8.8,20.3,8.8 - 20.3,11.9-14.9,NaN
3343,Households With Children Where Any Child Had A...,By State,Wyoming,Wyoming,3.5,48,"Jul 27 - Aug 8, 2022",07/27/2022,08/08/2022,10.7,6.6,16.2,6.6 - 16.2,8.6-11.8,NaN

In [699]:
# Check for any missing values in each column
print(df_Telemedicine.isnull().sum())

Indicator                    0
Group                        0
State                        0
Subgroup                     0
Phase                        0
Time Period                  0
Time Period Label            0
Time Period Start Date       0
Time Period End Date         0
Value                      240
Low CI                     240
High CI                    240
Confidence Interval        240
Quartile Range            1202
Suppression Flag          3292
dtype: int64

In [702]:


# Conditional calculations
# Example: Calculating average for a subgroup
subgroup_average = df_Telemedicine[df_Telemedicine['Subgroup'].total()]
print(subgroup_average)

AttributeError: 'Series' object has no attribute 'total'